title: "Golfin' Slayer Blog"
author: "Pseudomancer Studios"
description: "Blog site for Golfin Slayer!" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "golfin.slayer@gmail.com"
# twitter_username: "twitteruser"
# github_username: "githubuser"
# linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
instagram_username: golfin.slayer
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

baseurl: https://dillon-luong.github.io/gsr.github.io-site/

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

# this auto creates title var from the first markdown heading in a file
# strip_title prevents it from being rendered twice (once as an auto-gen title and again as the heading)
# collections: extends this behavior to collections (_posts) not just top-level pages
titles_from_headings:
  strip_title: true
  collections: true

header_pages:
  - archive.md

defaults:
  - scope:
      path: ""
      type: post
    values:
      layout: "post"
      tags: Other
